name: CI

on:
  push:
      branches: [master]

jobs:
  build:
    runs-on: macos-arm64

    defaults:
      run:
        shell: arch -arch arm64e bash -l -eo pipefail {0}

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: ./other/download_libs.sh

      - run: |-
          cat <<EOF > ./options.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>destination</key>
              <string>export</string>
              <key>method</key>
              <string>mac-application</string>
          </dict>
          </plist>
          EOF

      - name: Build
        run: xcodebuild -project iina.xcodeproj -scheme iina -config Release -archivePath ./archive archive

      - name: Export
        run: xcodebuild -archivePath archive.xcarchive -exportArchive -exportPath 'exportedApp.app' -exportOptionsPlist ./options.plist

      - uses: actions/upload-artifact@v2
        with:
          name: IINA
          path: exportedApp.app
